### ISSUE TITLE
MFlowInter is broken (green bands shown)

### ISSUE THREAD

**Issue by nu774** [pinterf/mvtools#1]
test script:

```
a = LSMASHVideoSource(...)
sup = a.MSuper(pel=1)
fw = sup.MAnalyse(isb=false, delta=1, overlap=4)
bw = sup.MAnalyse(isb=true, delta=1, overlap=4)
a.MFlowInter(sup, bw, fw, time=50, thSCD1=400)
```

**Comment by pinterf** [comment]
32 or 64 bit? I hope, this bug is among Fizick's general mvtools fixes. His
last version is 2.5.11.22 now

2016-04-27 4:11 GMT+02:00 nu774 notifications@github.com:

**Comment by nu774** [comment]
Both of 32bit and 64bit are broken.
As for 32bit, I know that 2.5.11.3 was OK, and haven't tried 2.5.11.22. Where can I download 2.5.11.22?
As for 64bit, mvtools_2.6.0.5_x64 was also broken in the same way. Haven't seen correctly working 64bit build.

**Comment by nu774** [comment]
OK, I tried 2.5.11.22 (32bit only) and it's OK.
I saw the following Fizick's comment, but I'm not sure how the fix relates to this:
•Fixed Mflow broken in 2.5.11.2, fixed several other small bugs.

As far as I can see, MflowInter of 2.5.11.2 and 2.5.11.3 didn't have this green-band issue.

**Comment by pinterf** [comment]
Huh, finally... Could you please test it? I made a pre-release of it

**Comment by nu774** [comment]
Looks fine now. Thanks a lot!
