### ISSUE TITLE
MDepan zerow doesn't seem to work

### ISSUE THREAD

**Issue by veins1** [pinterf/mvtools#12]
I'm using mdepan on mvtools vectors to stabilize with DePanStabilize. The problem is that with static shots "local" motion (moving hand) causes unnecessary stabilization. I tried tweaking zerow parameter of MDepan but it doesn't do anything. 
I'm not an expert but I think the problem is line 537 of MVDepan.cpp

**Comment by pinterf** [comment]
Thanks. This bug was probably there since the zerow parameter was introduced, The old local variable was not removed so it was overriding the parameter.
