### ISSUE TITLE
MFlowInter: System exception with certain combination of blksize, overlapv, divide and thSCD1

### ISSUE THREAD

**Issue by zorrozork** [pinterf/mvtools#13]
MFlowInter causes "System exception - access violation at 0x56f8c3bf, reading from 0x7c6b000".

This occurs with a certain combination of parameters: 
MAnalyze with blksize=16, overlapv=4 and divide=1 or 2.
MFlowInter with thSCD1=100 or larger. 

The exception occurs on some video frames when thSCD1 is between 81 and 100, but always occurs when the threshold is large enough. It didn't occur with threshold 80 or below. I think the source video will affect which threshold triggers the bug.

Changing the overlapv to any other valid value 0, 2, 6 or 8 makes the bug disappear. Using divide=0 makes it go away too.

It's possible to trigger the bug with other block sizes, for example using blksize=32 and overlapv=8.

I have attached a small script which triggers the exception, just change the AVISource.
My system is Windows 10, Avisynth v.2.6.0 ST, 32-bit, MVTools version is v2.7.26.

[mvtools_mflowinter_bug.avs.txt](https://github.com/pinterf/mvtools/files/1864709/mvtools_mflowinter_bug.avs.txt)

**Comment by pinterf** [comment]
Thanks (special thanks for the proper report), must be an ancient bug, probably fixed in this commit:
https://github.com/pinterf/mvtools/commit/91fd4d7abacd5ed422b70e4b48fd82ae72ccb91e

**Comment by zorrozork** [comment]
Special thanks for fixing it so quickly! 
Are you going to do a new release shortly?

**Comment by pinterf** [comment]
Released

**Comment by zorrozork** [comment]
I can confirm that the bug is fixed. Thank you, this fix will actually help a lot with my little project.
