### ISSUE TITLE
MFlowFps: System exception with certain combinations of pel, blkSize, overlap and divide with YV12 clips

### ISSUE THREAD

**Issue by zorrozork** [pinterf/mvtools#17]
MFlowFps causes "System exception - access violation at 0xf7dc0da, reading from 0x15ae41fc".

This happens with YV12 clips (YV24 and YUY2 are immune) and some combinations of pel, blkSize, overlap and divide. Also dct can affect the frequency of the crash (with dct=5 crashes less often). With pel=1 there are no crashes. With pel=4 there's more frequent crashing than with pel=2. 

Some examples:
blkSize 4, overlap 0, divide 0 -> works
blkSize 4, overlap 2, divide 0 -> crash (except with dct=5 works on some frames)
blkSize 8, overlap 4, divide > 0 -> crash sometimes, frequency depends on pel and dct
blkSize 16, overlap 8, divide 0-2 -> works

I have attached a small script which can be used to test the issue.
My system is Windows 10, Avisynth v.2.6.0 ST, 32-bit, MVTools version is the latest v2.7.32.

The frame size of the source clip was 720x680 in these tests.

[bug.zip](https://github.com/pinterf/mvtools/files/2497517/bug.zip)

**Comment by Seedmanc** [comment]
For me it sometimes gives another error (randomly), instead of access violation it says "MFlowFPS can't work in reentrant MT mode", independent of the internal MT setting and without any external MT applied.

It seems to depend on source resolution too, happens more often at higher res (tested on 720p).

**Comment by pinterf** [comment]
That second error must be the side effect of the main crash. I have a suspect, marked as todo recently, I will go on inspecting.

**Comment by pinterf** [comment]
Could you please have a look at this version?
https://drive.google.com/open?id=1rPnzqUYmE9UuHOrn1bk8QR3Q6tsnkh45

**Comment by zorrozork** [comment]
> 
> 
> Could you please have a look at this version?
> https://drive.google.com/open?id=1rPnzqUYmE9UuHOrn1bk8QR3Q6tsnkh45

I can't trigger the error anymore, seems like it's fixed. 
How's it working for you Seedmanc?

**Comment by pinterf** [comment]
Thanks you, release done. This must be a very old bug, even if not always triggered, depending on the current memory allocation layout. I've already fixed it in MFlowBlur long ago, but this fix is a generalized one for the other MFlow methods as well.

**Comment by Seedmanc** [comment]
Seems to be working fine, thanks.

**Comment by zorrozork** [comment]
I have run over 10 000 parameter combinations and there's no crashing anymore. Case closed. Thanks!
