### ISSUE TITLE
MCompensate crashes with overlap=0

### ISSUE THREAD

**Issue by Seedmanc** [pinterf/mvtools#21]
With a script as simple as this one:
```
FFmpegSource2("f:\avsoptim\24-1200.mkv") #1280x720 8bit YV12
mt=!true   
super = MSuper(mt=mt)  
fv = MAnalyse(super, mt=mt) #, overlap=2)
MCompensate(super, fv,  mt=mt)
```
With MT=false it just raises the error window, but with MT=true it crashes the app it's running in. Happens in both x64 and x86. Sometimes it won't crash on opening, but will on seeking. Setting overlap as little as 2 is enough to avoid the problem, doesn't seem to depend on blocksize. 
Sample video: https://mega.nz/#!R9x2SKQI!t8S1SX5DghZ-r-L83cJXnJvncd6gnnPQEFVivr06skg

**Comment by pinterf** [comment]
Ouch, thanks. Fix is coming ASAP.

**Comment by Seedmanc** [comment]
Thanks.
