### ISSUE TITLE
high bits DegrainX with 8 bits vectors produces green artefacts

### ISSUE THREAD

**Issue by erazortt** [pinterf/mvtools#23]
Using version 2.7.38. From the documentation: "It is possible to Degrain a 16 or 32 bit clip (and Super) with motion vectors created from a 8 bit clip."

The following script produces green artefacts which can be seen especially on the bottom of the frame and predominatly on dark frames:

input = input.ConvertBits(16)
srchSuper = input.ConvertBits(8,dither=1).MSuper( )
vmulti = srchSuper.MAnalyse( multi=true, delta=1 )
o_super = input.MSuper(levels=1)
return input.MDegrainN(o_super, vmulti, 1, plane=4)

Using plane=0 does also produce artefacts, these are however much harder to spot. I also tested with MDegrain1 instead of MDegrainN, with exactly the same result.

Example output:
[https://drive.google.com/open?id=1xfI2uBeQ3fxPh_z8vrkFABZs23QZ6nTg](https://drive.google.com/open?id=1xfI2uBeQ3fxPh_z8vrkFABZs23QZ6nTg)

**Comment by pinterf** [comment]
Thanks, from your pic I can see than the top 740 lines (out of total of the 800) are O.K. (are they?), and the bottom 60 lines has artifacts. (MDegrain1 and N is the same in this case because no special thSAD2 or thSADC2 was given).

**Comment by erazortt** [comment]
Yes the just the bottom 60 lines or so. In the meantime I found out that adding a black border of exactly 32 pixels at the bottom resolves the issue. Thus the frame height is then divisible by 64. However, for more than 99% of the frames it was already enough to add a border of just 2 black pixels, which makes things very confusing. Adding however a white border of 2 pixels instead of a black one solved the issues for all frames I was willing to look at in a 4 hour movie..

**Comment by erazortt** [comment]
Now I also found frames where adding a border did not solve the issue, apart of course of adding 64 lines of border...

**Comment by pinterf** [comment]
Check the v39 release please, it solved the problem for me.

**Comment by erazortt** [comment]
yeah seems to have been solved! Wow that was faster than I expected, awesome!
