### ISSUE TITLE
Frames distortion with chroma=False

### ISSUE THREAD

**Issue by ghost** [pinterf/mvtools#25]
I also reported this in the vapoursynth-mvtools repo. Dubhater told me to report this issue to you for further confirmation on whether this is a bug or not.

According to [MVTool's documentation](https://avisynth.org.ru/mvtools/mvtools2.html#examples), it is possible to use `chroma=False` in the Super phase for frame interpolation. Below is the example from the webpage itself:

```
To double fps with MFlowFps for fastest (almost) real-time playing:

AVISource("c:\test.avi") # or MPEG2Source, DirectShowSource, some previous filter, etc
# assume progressive PAL 25 fps or NTSC Film 23.976 source
super = MSuper(pel=1,hpad=0,vpad=0,chroma=false)
backward_vec = MAnalyse(super, blksize=32, isb = true, chroma=false, searchparam=1,search=0)
forward_vec = MAnalyse(super, blksize=32, isb = false, chroma=false, searchparam=1,search=0)
MFlowFps(super, backward_vec, forward_vec, num=2*FramerateNumerator(last), \
   den=FramerateDenominator(last), mask=0)
```

Here are the results when a user puts `chroma=False` in `MSuper` or `mv.Super`.

---

Example: Pinterf's MVTools 2.7.40

![VirtualDub64_SB3qbiPKcM](https://user-images.githubusercontent.com/40442071/56858639-77c21480-6932-11e9-8c99-27c736c4858b.png)

```
source = FFmpegSource2("C:\Users\Paul\Desktop\vs\hob.mp4", atrack=-1)

s = MSuper(source, hpad=16, vpad=16, rfilter=4, pel=1, chroma=False)
bv = MAnalyse(s, isb=True, blksize=16, chroma=False, lsad=2400, pnew=128, pglobal=256)
fv = MAnalyse(s, blksize=16, chroma=False, lsad=2400, pnew=128, pglobal=256)
MBlockFPS(source, s, bv, fv, num=60, den=1, mode=0)
```

---

Example: vapoursynth-mvtools v21

![VirtualDub64_rmjXNWcT33](https://user-images.githubusercontent.com/40442071/56858647-9fb17800-6932-11e9-951d-ad553d14f970.png)

```
import vapoursynth as vs
core = vs.core

source = core.ffms2.Source(r'C:\Users\Paul\Desktop\vs\hob.mp4')

s = core.mv.Super(source, hpad=16, vpad=16, rfilter=4, pel=1, chroma=False)
bv = core.mv.Analyse(s, isb=True, blksize=16, chroma=False, lsad=2400, pnew=128, pglobal=256)
fv = core.mv.Analyse(s, blksize=16, chroma=False, lsad=2400, pnew=128, pglobal=256)
c = core.mv.BlockFPS(source, s, bv, fv, num=60, den=1, mode=0)

c.set_output()
```

---

**Notes:**
- In Block/FlowFPS, the non-interpolated frames do not have the distortion
- Frames still get interpolated as they should (it's only the colors that get messed up)
- This happens to 
  - `mv.FlowFPS` and `MFlowFPS`
  - `mv.FlowBlur` and `MFlowBlur`

This might be a mistake in the MVTools' documentation or a bug inherited from the old MVTools.

**Comment by pinterf** [comment]
Thanks for report, the example is fixed in the documentation. Interpolation is based by the super clip so if U/V chroma planes are not generated for super, their content is 'undefined'. You can find an updated documentation in mvtools2.html.
