### ISSUE TITLE
Using 8x8 block size is half as fast as 16x16 and up

### ISSUE THREAD

**Issue by magnetite2** [pinterf/mvtools#29]
While using a script such as TemporalDegrain2 with an 8-bit source, changing the block size from 8 to any value up to 64 that I tested makes the script twice as fast. I was reading in the patch notes that some blocksizes (not specified which ones) were optimized with the newer AVX2 instructions and others weren't. Could this be the reason for the slowdown?

**Comment by pinterf** [comment]
Not really. 8x8 block size means that there are approximately 4x more motion blocks to handle than in the 16x16 case. Imagine it as the screen was covered with a denser grid. It affects the noise reduction part as well.

**Comment by magnetite2** [comment]
So more computations to do? I get it now. Thanks
