### ISSUE TITLE
mmask not work as before

### ISSUE THREAD

**Issue by realfinder** [pinterf/mvtools#3]
with [smam_mask()](http://pastebin.com/ui2uVy9V).Converttoy8()

in mvtools-v2.5.11.22 and 2.6.0.5 and even mvtools2_2.7.0.22d

http://i.imgur.com/qrCxnNr.png

in last pinterf mod

http://i.imgur.com/EpYLJ4N.png

**Comment by pinterf** [comment]
Confirmed, thanks. It seems that a nasty inline asm resizer that was moved into intrinsics, fails.

**Comment by realfinder** [comment]
thanks, just saw your PM in doom9 and sent you the replied :)

**Comment by pinterf** [comment]
Fixed in https://github.com/pinterf/mvtools/commit/99b178b9a06750b60cc0110952b6c9a5fcb87413 and https://github.com/pinterf/mvtools/commit/8c1e0f60a633e2cb339af41ccb8f5802b0a21085
