### ISSUE TITLE
Mutex ambiguity

### ISSUE THREAD

**Issue by eblanca** [pinterf/mvtools#32]
I see into DCTFFTW.cpp the statements

https://github.com/pinterf/mvtools/blob/c24e335ce2186e474fecde0cec1ecec2d8fee239/Sources/DCTFFTW.cpp#L103
https://github.com/pinterf/mvtools/blob/c24e335ce2186e474fecde0cec1ecec2d8fee239/Sources/DCTFFTW.cpp#L115

and the second one is into the destructor.
Now, I find it weird having in this same module two "lock" calls and no "unlock", could those need a review?

**Comment by pinterf** [comment]
Lock guard is a RAII object, release is done when it gets out of scope that is at function exit.

**Comment by eblanca** [comment]
Ok, thanks
