### ISSUE TITLE
Different results for the same MDegrain2 sessions

### ISSUE THREAD

**Issue by pinterf** [pinterf/mvtools#34]
As described in 
https://forum.doom9.org/showthread.php?p=1913919#post1913919

Bug not seen in 2.5.11.22
Bug exists even is 2.6.0.5

"The differences are in the heap of different pixels in the heap of different frames, and as a rule, starting from about the middle of the video with a length of 3 minutes. Visually, these differences are almost imperceptible, but they are, and there are a lot of them, and this I think affects the quality of compression of MPEG4 codecs."

"How to check this problem?
You make 3 attempts to encode the same AVS file in a row, you get 3 different AVI files. As a rule, their length will be slightly different, already by this sign it can be judged that there are differences in the frames. But even if in two of the three AVI files the length is the same, then anyway, by bitwise comparing them (fc /b file1.avi file2.avi >log), it turns out that they have differences."

**Comment by pinterf** [comment]
MAnalyze mt=false resolves the problem. The inconsistent behaviour is avstp/internal multithreading related.

**Comment by pinterf** [comment]
Comments in
2aeb598833ced4469c84d471e1637bd25f0febdf
and in the html docs at MAnalyse

**Comment by realfinder** [comment]
don't know if cretindesalpes fix this https://forum.doom9.org/showpost.php?p=1925268&postcount=1131 "FlowFPS, FlowInter and MMask: fixed a memory intialization bug that could produce slightly different results each run. Thanks to dubhater for the fix.
MAnalyse, MRecaculate: fixed block size parameter check in divide mode. Thanks again to dubhater."

anyway I did compare old mvtools by cretindesalpes with new one using winmerge
[full.zip](https://github.com/pinterf/mvtools/files/5351048/full.zip)
[filesonly.zip](https://github.com/pinterf/mvtools/files/5351081/filesonly.zip)

seems there are many changes

**Comment by pinterf** [comment]
From 2.6.1 changelog:
"FlowFPS, FlowInter and MMask: fixed a memory intialization bug that could produce slightly different results each run. Thanks to dubhater for the fix."
I fixed that memory initialization bug earlier but dubhater found it as well.
https://github.com/pinterf/mvtools/blob/mvtools-pfmod/Sources/MaskFun.cpp#L125

"MAnalyse, MRecaculate: fixed block size parameter check in divide mode. Thanks again to dubhater."
Already fixed as well.
https://github.com/pinterf/mvtools/blob/mvtools-pfmod/Sources/MVAnalyse.cpp#L205
Side note: 2.6.1 is wrong: the || was put on the wrong place in MVAnalyse.cpp and MVRecalculate.cpp)
if (_divide != 0 || (_blksizex < 8 && _blksizey < 8))
instead of
if (_divide != 0 && (_blksizex < 8 || _blksizey < 8))

I'm not comparing them deeper (2.6.0.5 and 2.6.1); no git (at least I am not aware of), manual and visual source comparison is time consuming.
And comparing 2.6.1 with current mvtools source does not help. You can follow all those changes in my git project (since my origin was v2.6.0.5)

**Comment by realfinder** [comment]
yes, you right, there are no git, and that why I give you diff files for 2.6.1 with 2.6.0.5 as small help

and I don't know why cretindesalpes did these updates in this way in 2020 instead of participating in this fork, I think they still avs 2.5 with hacked header for avs 2.6 colors, same for dither tools

maybe only "MDepan: parameter zerow is now actually taken into account." need to added

**Comment by pinterf** [comment]
Yeah, thanks for the diff. 
I think even 2.5.11.22 changes which happened since then were not incorporated.
MDepan: I've seen that, I'll check it later.

**Comment by realfinder** [comment]
> 
> 
> I think even 2.5.11.22 changes which happened since then were not incorporated.

that was done thanks to you :)
![image](https://user-images.githubusercontent.com/2512153/95568260-ae0f2900-0a2c-11eb-92ce-dc46816f76b0.png)

edit: also https://github.com/pinterf/mvtools/releases/tag/r2.7.0.22

**Comment by pinterf** [comment]
In my fork, yes, but not in the 2.6.0.5

**Comment by realfinder** [comment]
this issue should close, right?
![image](https://user-images.githubusercontent.com/2512153/110219317-833bda80-7ecf-11eb-94af-28c84a765366.png)

anyway, I think

> maybe only "MDepan: parameter zerow is now actually taken into account." need to added

is forgotten?

**Comment by pinterf** [comment]
Yep. I'm gonna close this now.
As for the other one (MDepan): pls. open an issue, thx.
