### ISSUE TITLE
MV bug

### ISSUE THREAD

**Issue by AverageUnknown** [pinterf/mvtools#35]
with : https://github.com/realfinder/AVS-Stuff/blob/Community/avs%202.5%20and%20up/DFMDeRainbow.avsi

Script: 

```
colorbars()
converttoy8
DFMDeRainbow_FluxsmoothSTMC
```
or
```
colorbars()
converttoy8
DFMDeRainbow(mask=false,interlaced=false,use_Flux5framesT=true,mc=true)
```
With motion compensation on it crashes everytime.

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "avsp.pyo", line 5003, in local_wnd_proc
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by pinterf** [comment]
Could you please test with the v43 just released

**Comment by AverageUnknown** [comment]
works great thank you!
