### ISSUE TITLE
Cannot run mvtools on Windows 10

### ISSUE THREAD

**Issue by bfulop** [pinterf/mvtools#4]
Hello,

I'm trying to use mvtools with MeGui, but I either get a _"module not found"_ (64bit version) or memory exception error (x86 version). I have copied the mvtools2.dll file into the tools\avisynth_plugin folder.
I have the exact same setup on a Windows 7 machine where it works great. On the Windows 10 machine I have successfully used other plugins e.g. svpflow. 
I tried dependency walker, but it gave so many error messages that I couldn't figure out what could be the real issue.

Does mvtools use any special dependencies that I have to install on my computer?

**Comment by pinterf** [comment]
It needs only VS2015 Redistributables Update 3.
https://www.microsoft.com/en-us/download/details.aspx?id=53840
Additionally it loads fftw3 library in SysWOW64 (either libfftw3f-3.dll or fftw3.dll but there it is delay-loded and has a specific error message on that.

**Comment by bfulop** [comment]
Köszi a segítséget! :)

So finally I managed to get a more descriptive error message using AVSMeter:

```
Cannot load file 'C:/Program Files (x86)/AviSynth+/plugins+/mvtools2.dll'.

Dependencies that could not be loaded:
  MSVCP140.dll
  VCRUNTIME140.dll

Note: "Visual Studio 2015 Runtime doesn't seem to be installed"
```

By the way, the dlls you provided are for Avisynth or AviSynth+? I'm completely new to all this, just looking for a way to add some motion blur to my movies...

**Comment by bfulop** [comment]
And it took me to the same download link that you provided. I don't know why it didn't work the first time I tried...

It seems to be running well now, albeit only using one CPU core... This is not related to your library.

Thanks for the help!
