### ISSUE TITLE
adding MVTools 2.6.1.0 change in MDepan

### ISSUE THREAD

**Issue by realfinder** [pinterf/mvtools#41]
MVTools 2.6.1.0 https://forum.doom9.org/showpost.php?p=1925268&postcount=1131

old mvtools by cretindesalpes (2.6.0.5) compare file with 2.6.1.0 using winmerge
https://github.com/pinterf/mvtools/files/5351048/full.zip
https://github.com/pinterf/mvtools/files/5351081/filesonly.zip

**Comment by pinterf** [comment]
The last one which I didn't check but did it now: I fixed zerow issue three years ago 
https://github.com/pinterf/mvtools/commit/e566348c1cbd12c248ebeb0c514c3b888a3a9f26
```
2.7.27 (20180318)
Fix: MDepan: use zerow parameter. The parameter had no effect probably since it was introduced
```
