### ISSUE TITLE
Memory leak in MFlowFPS

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [pinterf/mvtools#58]
Memory leak in MFlowFPS
Something is wrong with the function call or it's destructor. If you put the function in the avisynth runtime environment it begins to eat memory in linear fashion, seems with each function call (ie per every frame). It does not stop by itself, eventually no free RAM remains and so it expands into extensive pagefile usage.
The issue seems to be an old one - reproducible even for mvtools v2.7.17.22.
I also checked MBlockFPS and MFlowBlur, they seem to be Ok.  Probably can be useful for comparison.

test code
...
ScriptClip (""" myFRC() """)
function myFRC (clip c) {
  c
  sc = MSuper()
  bv = sc.MAnalyse (isb=true)
  fv = sc.MAnalyse (isb=false)
  MFlowFps ( sc, bv, fv )
 }

**Comment by pinterf** [comment]
You are right. Thanks for the report, I'll be back soon (some days probably) with a version to look at.

EDIT: Could you please check this build if everything is OK? If so, I'm gonna release.
https://drive.google.com/uc?export=download&id=1mbZeQD5BLa3N9_Cgs7H_KX6HeDoVByW1

**Comment by pinterf** [comment]
(zero response, did not release)
