### ISSUE TITLE
Please specify smmintrin.h and emmintrin.h, VS2017 missed it.

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/mvtools#6]
Also the /FS should be added to the C++ command.

**Comment by pinterf** [comment]
Includes added.
Why /FS is needed?

**Comment by fuchanghao** [comment]
Because I can't build the whole solution by the error below, I have to build the dll one by one.

Fatal Error C1041 	cannot open program database 'file'; if multiple CL.EXE write to the same .PDB file, please use /FS

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-fatal-errors-c999-through-c1999

**Comment by fuchanghao** [comment]
thanks fixed
