### ISSUE TITLE
Why the DePanEstimate have to use WindowsSdk_71A library in win32 build?

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/mvtools#7]
I wanna to know the reason to use WindowsSdk_71A_ExecutablePath instead of WindowsSdk_ExecutablePath for example like the x64 build.

**Comment by pinterf** [comment]
Oops, I missed this one. WindowsSdk_71A_ExecutablePath appears everywhere along with WindowsSDK_ExecutablePath, so it's not "instead" but "with" (at least now - in 2019).
